SET DEFINE OFF;
Insert into SFA.LST_OFFICES
   (OFFICE_ID, OFFICE_NAME, OFFICE_CODE, OFFICE_TYPE, MOTHER_OFFICE_ID, 
    EFFECTIVE_DATE, CONTRACT_DATE, CONSENT_DATE, OPENING_DATE, CLOSING_DATE, 
    STATUS, CLOSING_REASON, PROVINCE, DISTRICT, WARD, 
    ADDRESS, OFFICE_TEL, FAX, GA_OWNER, GA_OWNER_NO, 
    GA_TAX_CODE, GA_COMPANY, GAD, GA_TYPE, GA_CLASSIFY, 
    GA_EMAIL, REMARKS, CS1, CS2, SA, 
    PACKAGE_TYPE, Y1_PER, Y2_PER, RECELL_PER, BANK_ACCOUNT, 
    BENEFICIARY, BANK_CODE, BRANCH_CODE, LIMIT_GA, GA_CONTRACT, 
    GA_CONTRACT_EXP, RENEW_CONTRACT, RENEW_DATE, RENEW_EFFECTIVE_DATE, DEPOSIT_DATE, 
    DEPOSIT_AMOUNT, CREATIONDATE, CREATEDBY, LASTUPDATEDDATE, LASTUPDATEDBY, 
    ISACTIVE, BRANCH_MANAGER)
 Values
   (21, 'GA Quoc Oai, North', '207', '2', 1920, 
    TO_DATE('7/28/2019', 'MM/DD/YYYY'), TO_DATE('7/29/2019', 'MM/DD/YYYY'), TO_DATE('3/5/2019', 'MM/DD/YYYY'), TO_DATE('8/18/2019', 'MM/DD/YYYY'), NULL, 
    4, NULL, 63, 61, 62, 
    'Lô 9B, DG 02, Đường Bắc Nam', '(0246) 3270 777', NULL, NULL, NULL, 
    NULL, 'Công ty TNHH Phú An Khang Hưng Thịnh', '143096039', NULL, 2, 
    'dungtran.GAD@tvbh.hanwhalife.com.vn', NULL, '143240130'||CHR(13)||CHR(10)||'143240130', '143120483', '143069361', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, TO_DATE('9/14/2021 7:29:23 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 
    1, 'Nguyễn Văn Minh');
Insert into SFA.LST_OFFICES
   (OFFICE_ID, OFFICE_NAME, OFFICE_CODE, OFFICE_TYPE, MOTHER_OFFICE_ID, 
    EFFECTIVE_DATE, CONTRACT_DATE, CONSENT_DATE, OPENING_DATE, CLOSING_DATE, 
    STATUS, CLOSING_REASON, PROVINCE, DISTRICT, WARD, 
    ADDRESS, OFFICE_TEL, FAX, GA_OWNER, GA_OWNER_NO, 
    GA_TAX_CODE, GA_COMPANY, GAD, GA_TYPE, GA_CLASSIFY, 
    GA_EMAIL, REMARKS, CS1, CS2, SA, 
    PACKAGE_TYPE, Y1_PER, Y2_PER, RECELL_PER, BANK_ACCOUNT, 
    BENEFICIARY, BANK_CODE, BRANCH_CODE, LIMIT_GA, GA_CONTRACT, 
    GA_CONTRACT_EXP, RENEW_CONTRACT, RENEW_DATE, RENEW_EFFECTIVE_DATE, DEPOSIT_DATE, 
    DEPOSIT_AMOUNT, CREATIONDATE, CREATEDBY, LASTUPDATEDDATE, LASTUPDATEDBY, 
    ISACTIVE, BRANCH_MANAGER)
 Values
   (1, 'Dak Lak, Central', '100', '1', 1, 
    TO_DATE('5/20/2021', 'MM/DD/YYYY'), TO_DATE('5/20/2021', 'MM/DD/YYYY'), TO_DATE('5/20/2021', 'MM/DD/YYYY'), TO_DATE('5/20/2021', 'MM/DD/YYYY'), NULL, 
    1, NULL, 63, 61, 62, 
    'Lầu 3, Tòa Nhà Bưu Điện Ngã 6, Số 1-3 Nơ Trang Long', NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, '142689639142689639', '143035150', '143054771', 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, NULL, NULL, 
    NULL, NULL, NULL, TO_DATE('9/14/2021 8:40:20 PM', 'MM/DD/YYYY HH:MI:SS AM'), -1, 
    1, 'Lê Văn Hóa');
COMMIT;
